# Generated by Django 2.2.6 on 2021-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210618_1810'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='No_repeat_follows',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='No_repeat_follows'),
        ),
    ]
